### PR TITLE
Add account link to corporate bar

### PR DESCRIPTION
**Pull request by csexton**
Currently there is no good way to go back and see account details or edit teams from the different apps. This add a very minimal "Account" link to the black bar. This way there is at least some path to finding your way back to Kracken so that passwords can be changed, teams can be edited, etc.

image

### CODE REVIEW

**Comment by davidhelms** [comment]
Yay!!!

**Comment by csexton** [comment]
I really wanted to do a popover with more options, but after 30 min I realized it was gonna be a time-sink. Punted for now--but at least we have *something*

**Comment by syoder** [comment]
Cool!

Would it make sense to also have a `Teams` link?  It may just be because I'm a Radius Employee and I'm on a million teams, but that's a place I commonly need to go also.

**Comment by csexton** [comment]
Just adding the teams link would be easy -- I was just hesitant to add too many items.

Do we like this list?

- Store
- Account
- Teams
- Sign Out

**Comment by cupakromer** [comment]
:+1: for the list

**Pull request merged**
