### PR TITLE
Radiusnetworks flybuy brand update

### PR DESCRIPTION
**Pull request by jcavena**
Update the headers in iris, kracken (and any other app that uses this gem) to the new co-branded flybuy and radius networks logo and colors. 

Fixes: https://github.com/RadiusNetworks/iris/issues/5038
Fixes: https://github.com/RadiusNetworks/kracken/issues/699

image

image

image

image

image

image

Updated the User icon in the shared topnavbar to include the welcome message: 
image

### CODE REVIEW

**Comment by JamSawyer** [comment]
Per the convo in #design-dev, still a bit blurry 🤔 .

@jcavena, for the Iris work, one of the requirements is to add `Welcome, <first name>` like kracken has. Will that be in a separate PR?

@jnebeker @emilyrwhite - I didn't spin up a ticket for Captain, just mentioned it in the body of requirements which I realize is sneaky and under the radar. Is it fair that I spin up a ticket for captain, for another sprint?

**Comment by jcavena** [comment]
@JamSawyer Add issues to those repos and we can link them here _if_ those repos use the gem. Otherwise they can be updated individually. We can also link all related issues to the `iris` one to keep track of them.

**Comment by jcavena** [comment]
@JamSawyer I'm installing Captain to check the UI. I updated the `iris` UI via the gem to include the welcome message. But unsure how much it is used in Captain. It may need some TLC separately from this gem.

**Review by JamSawyer — COMMENTED** [review]
@piya-das @jcavena these still look a little fuzzy to me. Is that fuzziness resolved?

**Comment by jcavena** [comment]
@JamSawyer At this point I think it's the screenshots. They look ok to me now.

**Review by JamSawyer — APPROVED** [review]
JC walked me through the changes live - they look acceptable to me

**Pull request merged**
